spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/mailcraft
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
#for the project we use the update the schema
#for the production level we use the validate
spring.jpa.show-sql=true
